name: Continuous Integration - Frontend

on:
  pull_request:
    paths:
      - frontend/**
    branches:
      - dev
      - main

jobs:
  Quality Assurance:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create environment
        run: |
          sudo apt update -y
          sudo apt install nodejs npm
          cd frontend
          npm ci

      - name: Check formatting
        if: ${{ always() }}
        run: |
          cd frontend
          npm run format

      - name: Check linting
        if: ${{ always() }}
        run: |
          cd frontend
          npm run lint
