name: Build Images for Production & Push to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  build-images:
    name: Build Frontend/Backend Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: sirpaulmcd/task-app-backend:latest

      - name: Build and Push Frontend Image
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: sirpaulmcd/task-app-frontend:latest
